/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ps_input_validation.c                              :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mintan <mintan@student.42singapore.sg      +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/07/09 18:09:36 by mintan            #+#    #+#             */
/*   Updated: 2024/07/23 14:31:17 by mintan           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <limits.h>
#include "../../include/push_swap.h"
#include "../../include/libft.h"
#include "../../include/ft_printf.h"

/* Description: free all the elements in the string arr. */

static void	freeall(char **arr, int n)
{
	int	i;

	i = 0;
	while (i <= n)
	{
		free(arr[i]);
		i++;
	}
}

/* Description: Gets the arr size of a string array generated by ft_split. */

int	find_stray_sz(char **stray)
{
	int	stray_sz;

	stray_sz = 0;
	while (stray[stray_sz] != NULL)
	{
		stray_sz++;
	}
	return (stray_sz);
}

/* Description: Takes in a string and performs ft_split. Finds the array size of
   of the split string array. Frees the string arr and the strings inside
*/
int	find_arr_sz_split(char *str)
{
	char	**stray;
	int		stray_size;

	stray = ft_split(str, ' ');
	stray_size = find_stray_sz(stray);
	freeall (stray, stray_size);
	free (stray);
	return (stray_size);
}

/* Description: Takes in the input arguments from main and returns validates
   those inputs before returning an array of integers.
   Actions:
   1. argc = 2: splits the 2nd input into an array of string before validating
   2. argc > 2: validate the inputs normally
   3. Returns the array on integers generated from the validation function
*/

int	*ps_gen_intray(int argc, char *argv[])
{
	int		*ret;
	char	**stray;
	int		stray_sz;

	if (argc == 2)
	{
		stray = ft_split(argv[1], ' ');
		stray_sz = find_stray_sz(stray);
		ret = ps_validate_input(stray_sz, stray, 0);
		if (ret == NULL)
			return (freeall (stray, stray_sz), free (stray), NULL);
	}
	else
	{
		ret = ps_validate_input(argc, argv, 1);
		if (ret == NULL)
			return (NULL);
	}
	return (ret);
}
